/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'DMP Help Center',
    },
    { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = sidebars;
